spring:
  application:
    name: smart-hire-auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/smarthire_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info